// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUM_Vok0VvLqEapCYmgKuEU4PX6swOHiI',
    appId: '1:210197691154:web:3c26406bc752b603a051cb',
    messagingSenderId: '210197691154',
    projectId: 'nutriscan-uni-623a0',
    authDomain: 'nutriscan-uni-623a0.firebaseapp.com',
    storageBucket: 'nutriscan-uni-623a0.firebasestorage.app',
    measurementId: 'G-PE0MH5JTSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZgIiJsAhzBDxxsqruZbichycmfnqHME',
    appId: '1:210197691154:android:9b520e9f343f6854a051cb',
    messagingSenderId: '210197691154',
    projectId: 'nutriscan-uni-623a0',
    storageBucket: 'nutriscan-uni-623a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-tT6OiBrga0oIFVsaU0NimW_xTtEEZU',
    appId: '1:210197691154:ios:8d62899e89bd766ea051cb',
    messagingSenderId: '210197691154',
    projectId: 'nutriscan-uni-623a0',
    storageBucket: 'nutriscan-uni-623a0.firebasestorage.app',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-tT6OiBrga0oIFVsaU0NimW_xTtEEZU',
    appId: '1:210197691154:ios:8d62899e89bd766ea051cb',
    messagingSenderId: '210197691154',
    projectId: 'nutriscan-uni-623a0',
    storageBucket: 'nutriscan-uni-623a0.firebasestorage.app',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUM_Vok0VvLqEapCYmgKuEU4PX6swOHiI',
    appId: '1:210197691154:web:8e31eec88db924ffa051cb',
    messagingSenderId: '210197691154',
    projectId: 'nutriscan-uni-623a0',
    authDomain: 'nutriscan-uni-623a0.firebaseapp.com',
    storageBucket: 'nutriscan-uni-623a0.firebasestorage.app',
    measurementId: 'G-XBSYXW76L8',
  );
}
